NewMVC/Controllers/FlatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewMVC.Controllers
{
    public class FlatController : Controller
    {
        //
        // GET: /Flat/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CustomerAction()
        {
            return View("CustomerAngularView");
        }

        public ActionResult BootstrapMaterialDesign()
        {
            return View("BootstrapMaterialDesign");
        }

        public ActionResult Materialize()
        {
            return View("PaperElements");
        }

    }
}

NewMVC/Views/Flat/BootstrapMaterialDesign.cshtml
@{
    Layout = null;
    ViewBag.title = "Bootstrap Material Design";
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <title>@ViewBag.title</title>

   

</head>
<body ng-app="BootstrapMaterialModule">
    <div class="container">
        <div ng-view=""></div>


         @* @Scripts.Render("~/bundles/jquery")*@

           @* @Scripts.Render("~/bundles/js/frameworks")*@

            <script type="text/javascript" src="~/bower_components/jquery/dist/jquery.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular-route.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular-resource.min.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-animate.min.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-aria.min.js"></script>

            <!-- Angular Material Javascript now available via Google CDN; version 0.8 used here -->
            <script src="https://ajax.googleapis.com/ajax/libs/angular_material/0.8.3/angular-material.min.js"></script>

            @*Bootstrap Material Design Scripts*@

            <script type="text/javascript" src="~/bower_components/bootstrap-material-design/dist/js/material.js"></script>
            <script type="text/javascript" src="~/bower_components/bootstrap-material-design/dist/js/ripples.js"></script>

            <script type="text/javascript" src="~/Scripts/app/controllers/BootstrapMaterialController.js"></script>
            <script type="text/javascript" src="~/Scripts/app/modules/BootstrapMaterialModule.js"></script>

            <script type="text/javascript">

                $(document).ready(function () {
                    $.material.init();
                });

            </script>


    </div>


</body>
</html>

NewMVC/Views/Flat/CustomerAngularView.cshtml
@{
    Layout = null;
    ViewBag.title = "Customer Page";
}

<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.title</title>
    <link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css' />

    @Styles.Render("~/Content/css/frameworks")
    @*    @Styles.Render("~/Content/flat-ui")*@
    @Styles.Render("~/Content/css/Animate")


    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" />

    <link rel="shortcut icon" href="~/img/favicon.ico" />

    <!-- Angulars Material CSS now available via Google CDN; version 0.8 used here -->
   @* <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/angular_material/0.8.3/angular-material.min.css">*@

    <!-- default themes and core styles -->
    <link rel="stylesheet" href="bower_components/angular-material/angular-material.css" />

    <link rel="stylesheet" href="~/bower_components/bootstrap-material-design/dist/css/material.css" />
    <link rel="stylesheet" href="~/bower_components/bootstrap-material-design/dist/css/ripples.css" />
    <link rel="stylesheet" href="~/bower_components/bootstrap-material-design/dist/css/material-fullpalette.css" />
    <link rel="stylesheet" href="~/bower_components/bootstrap-material-design/dist/css/roboto.css" />

    <!-- extra, overriding theme files -->
    @*<link rel="stylesheet" href="bower_components/angular-material/themes/indigo-theme.css">*@

    <!-- Polymer files -->

    @*    <script type="text/javascript" src="~/bower_components/webcomponentsjs/webcomponents.min.js"></script>
    <link rel="import" href="~/elements/my-element.html" />*@


    <style type="text/css">
        .container {
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }

        #visible-row {
            -webkit-transition: 1s linear all; /* Chrome */
            -moz-transition: 1s linear all;
            -o-transition: 1s linear all;
            transition: 1s linear all;
        }

        .row {
            margin-top: 20px;
        }

        .selected {
            background-color: lightblue;
        }

        /*Material Design Styles*/

        .app-content {
            width: 100%;
        }

        form {
            padding: 10px 20px 30px 25px;
        }

        md-input-group.long > input {
            width: 100%;
        }

        md-card {
            margin: 0 30px 25px 30px;
        }

    </style>

</head>

<body data-ng-app="CustomerAngularMod">
    <div class="container">

        <div data-ng-view=""></div>


        @Scripts.Render("~/bundles/jquery")

        @Scripts.Render("~/bundles/js/frameworks")
        @Scripts.Render("~/bundles/flat-ui")
        <script src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

        @*<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/wow/1.0.3/wow.min.js"></script>*@

        @* @Scripts.Render("~/bundles/angularjs")*@

        <script type="text/javascript" src="~/bower_components/bootstrap-material-design/dist/js/material.js"></script>
        <script type="text/javascript" src="~/bower_components/bootstrap-material-design/dist/js/ripples.js"></script>

        <!-- Angular JS files -->

        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular-route.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.15/angular-resource.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-animate.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.6/angular-aria.min.js"></script>

        <!-- Angular Material Javascript now available via Google CDN; version 0.8 used here -->
        <script src="https://ajax.googleapis.com/ajax/libs/angular_material/0.8.3/angular-material.min.js"></script>

        <script type="text/javascript" src="~/Scripts/app/services/CustomerAngularService.js"></script>
        <script type="text/javascript" src="~/Scripts/app/services/MaterialService.js"></script>
        <script type="text/javascript" src="~/Scripts/app/factory/CustomerAngularFactory.js"></script>
        <script type="text/javascript" src="~/Scripts/app/controllers/CustomerAngularController.js"></script>
        <script type="text/javascript" src="~/Scripts/app/directives/directiveHelloWorld.js"></script>
        <script type="text/javascript" src="~/Scripts/app/directives/directiveMyElement.js"></script>
        <script type="text/javascript" src="~/Scripts/app/modules/CustomerAngularMod.js"></script>


        <!-- Directive Templates -->

        <script type="text/ng-template" id="helloWorld.html">

            <div class="panel panel-success">
        <div class="panel-heading">Custom Directive</div>
        <div class="panel-body">
            <div class="p" id="visible-row">
                <h2 id="directive-header"></h2>
                <h4>Directives are fun.</h4>
            </div>
        </div>
    </div>

        </script>

        <script type="text/ng-template" id="jumbo.html">

            <div class='jumbotron' id='first-jumbo'>
                <h1>Heading</h1>
                <p>This is jumbotron.{{id}}</p>
            </div>
            <div class='row'>
                <button type='button' id='btnChangeJumboText' class='btn btn-block btn-lg btn-success' data-ng-click='changeText();'>Change Text</button>
            </div>

        </script>

         @*firstModal Dialog*@

    <script type="text/ng-template" id="dialog1.tmpl.html">

<md-dialog aria-label="Mango (Fruit)">
  <md-content class="sticky-container">
    <md-subheader class="md-sticky-no-effect">Mango (Fruit)</md-subheader>
    <div class="dialog-content">
      <p>
        The mango is a juicy stone fruit belonging to the genus Mangifera, consisting of numerous tropical fruiting trees, cultivated mostly for edible fruit. The majority of these species are found in nature as wild mangoes. They all belong to the flowering plant family Anacardiaceae. The mango is native to South and Southeast Asia, from where it has been distributed worldwide to become one of the most cultivated fruits in the tropics.
      </p>
      <img style="margin: auto; max-width: 100%;" alt="Lush mango tree" src="http://thenextweb.com/wp-content/blogs.dir/1/files/2015/03/angularjs.jpeg">
      <p>
        The highest concentration of Mangifera genus is in the western part of Malesia (Sumatra, Java and Borneo) and in Burma and India. While other Mangifera species (e.g. horse mango, M. foetida) are also grown on a more localized basis, Mangifera indica—the "common mango" or "Indian mango"—is the only mango tree commonly cultivated in many tropical and subtropical regions.
      </p>
      <p>
        It originated in Indian subcontinent (present day India and Pakistan) and Burma. It is the national fruit of India, Pakistan, and the Philippines, and the national tree of Bangladesh. In several cultures, its fruit and leaves are ritually used as floral decorations at weddings, public celebrations, and religious ceremonies.
      </p>
    </div>
  </md-content>
  <div class="md-actions" layout="row">
    <md-button href="http://en.wikipedia.org/wiki/Mango" target="_blank" hide show-md>
      More on Wikipedia
    </md-button>
    <span flex></span>
    <md-button ng-click="answer('not useful')">
     Not Useful
    </md-button>
    <md-button ng-click="answer('useful')" class="md-primary">
      Useful
    </md-button>
  </div>
</md-dialog>

    </script>

    </div>

   

    <!-- Document ready script -->

        <script type="text/javascript">

            $(document).ready(function () {
                //new WOW().init();
                $.material.init();
            });

        </script>

</body>
</html>

NewMVC/Views/Flat/Index.cshtml
@{
    Layout = null;
    ViewBag.title = "Flat-UI Page";
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.title</title>
    <link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css' />

    @Styles.Render("~/Content/css/frameworks")
    @Styles.Render("~/Content/flat-ui")
    @Styles.Render("~/Content/css/Animate")

    <link rel="shortcut icon" href="~/img/favicon.ico" />

    <style type="text/css">
        .row {
            margin-top: 10px;
        }

        .page-header h1 {
            -moz-animation-delay: 0.3s;
            -o-animation-delay: 0.3s;
            -webkit-animation-delay: 0.3s;
            animation-delay: 0.3s;
        }

        .tile#tile1 {
            -moz-animation-delay: 0.7s;
            -o-animation-delay: 0.7s;
            -webkit-animation-delay: 0.7s;
            animation-delay: 0.7s;
        }

        .tile#tile2 {
            -moz-animation-delay: 1s;
            -o-animation-delay: 1s;
            -webkit-animation-delay: 1s;
            animation-delay: 1s;
        }

        .tile#tile3 {
            -moz-animation-delay: 1.3s;
            -o-animation-delay: 1.3s;
            -webkit-animation-delay: 1.3s;
            animation-delay: 1.3s;
        }

        .tile#tile4 {
            -moz-animation-delay: 1.6s;
            -o-animation-delay: 1.6s;
            -webkit-animation-delay: 1.6s;
            animation-delay: 1.6s;
        }

    </style>
</head>
<body data-ng-app="flatIndex">

    <div class="container">

        <div class="page-header" data-ng-controller="first">
            <a data-animation="animated pulse" href="@Url.Action("Index", "Flat")"><h1 data-animation="animated bounceInDown">{{propBanner.mainBanner}}</h1></a>
            <small>{{propBanner.subBanner}}</small>
        </div>
        <div class="row">
            <button class="btn btn-block btn-lg btn-inverse">Submit</button>
        </div>
        <div class="row">
            <div class="col-md-3">
                <select class="form-control select select-primary select-block mbl">
                    <optgroup label="First">
                        <option value="0">Item 1</option>
                        <option value="1">Item 2</option>
                        <option value="2">Item 3</option>
                        <option value="3">Item 4</option>
                    </optgroup>
                    <optgroup label="Second">
                        <option value="4">Item 5</option>
                        <option value="5">Item 6</option>
                    </optgroup>
                </select>
            </div>
            <div class="col-md-3">
                <select multiple="multiple" class="form-control multiselect multiselect-info">
                    <option value="0" selected>Item 1</option>
                    <option value="1">Item 2</option>
                    <option value="2">Item 3</option>
                    <option value="3">Item 4</option>
                    <option value="4">Item 5</option>
                </select>
            </div>
            <div class="col-md-3">
                <input name="tagsinput" class="tagsinput" data-role="tagsinput" value="Clean, Fresh, Modern, Unique" />
            </div>
            <div class="col-md-3">
                <div class="tagsinput-primary">
                    <input name="tagsinput" class="tagsinput" data-role="tagsinput" value="School, Teacher, Colleague" />
                </div>
            </div>
        </div>
        <div class="row">
            <div id="slider"></div>
        </div>
        <div class="row pbl">
            <div class="col-md-3">
                <input type="checkbox" checked data-toggle="switch" id="switch-01" />
            </div>
            <div class="col-md-3">
                <div class="bootstrap-switch-square">
                    <input type="checkbox" checked data-toggle="switch" id="custom-switch-03" data-on-text="<span class='fui-check'></span>" data-off-text="<span class='fui-cross'></span>" />
                </div>
            </div>
            <div class="col-md-3">
                <input type="checkbox" checked data-toggle="switch" data-on-color="success" data-off-color="warning" id="custom-switch-06" />
            </div>
            <div class="col-md-3">
                <input type="checkbox" checked data-toggle="switch" data-on-color="warning" data-off-color="info" id="custom-switch-07" />
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="tile" id="tile1" data-animation="animated bounceInUp">
                    <img src="@Url.Content("~/img/icons/png/Compas.png")" alt="Compass" class="tile-image big-illustration" data-animation="animated shake" />
                    <h3 class="tile-title">Web Oriented</h3>
                    <p>100% convertable to HTML/CSS Layout.</p>
                    <a class="btn btn-primary btn-large btn-block" href="#">Get Pro</a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="tile" id="tile2" data-animation="animated bounceInUp">
                    <img src="@Url.Content("~/img/icons/png/Infinity-Loop.png")" alt="Loop" class="tile-image" data-animation="animated shake" />
                    <h3 class="tile-title">Easy to Customize</h3>
                    <p>Vector-based shapes and minimum of layer styles.</p>
                    <a class="btn btn-primary btn-large btn-block" href="http://designmodo.com/flat">Get Pro</a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="tile" id="tile3" data-animation="animated bounceInUp">
                    <img src="@Url.Content("~/img/icons/png/Pensils.png")" alt="Pencils" class="tile-image" data-animation="animated shake" />
                    <h3 class="tile-title">Color Swatches</h3>
                    <p>Easy to add or change elements. Makes things cooler.</p>
                    <a class="btn btn-primary btn-large btn-block" href="http://designmodo.com/flat">Get Pro</a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="tile" id="tile4" data-animation="animated bounceInUp">
                    @*<img src="~/img/icons/svg/ribbon.svg" alt="Ribbon" class="tile-hot-ribbon" />*@
                    <img src="@Url.Content("~/img/icons/png/Chat.png")" alt="Chat" class="tile-image" data-animation="animated shake" />
                    <h3 class="tile-title">Free for Share</h3>
                    <p>Your likes, shares and comments helps us.</p>
                    <a class="btn btn-primary btn-large btn-block" href="http://designmodo.com/flat">Get Pro</a>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/js/frameworks")
    @Scripts.Render("~/bundles/flat-ui")
    @Scripts.Render("~/bundles/angularjs")

    <script type="text/javascript" src="~/Scripts/app/modules/FlatUIIndexMod.js"></script>
    <script type="text/javascript" src="~/Scripts/app/controllers/flatController.js"></script>

    <script type="text/javascript">

        function doAnimation(elems) {
            var animEndEv = "webkitAnimationEnd animationend";

            elems.each(function () {
                var $this = $(this),
                    $animationType = $(this).data('animation');

                $(this).addClass($animationType).one(animEndEv, function () {
                    $(this).removeClass($animationType);
                });
            });
        }

        $(document).ready(function () {
            $("select").select2({
                dropdownCssClass: 'dropdown-inverse'
            });

            $('.tile img[data-animation ^= "animated"]').hover(function () {
                
                var $this = $(this);
                doAnimation($this);
            });

            $(".page-header h1[data-animation ^= 'animated']").hover(function () {
                
                var $this = $(this);
                var animEndEnv = "webkitAnimationEnd animationend";
                var $animationType = $(".page-header a[data-animation ^= 'animated']").data('animation');
                
                $this.addClass($animationType).one(animEndEnv, function () {
                    $this.removeClass($animationType);
                });

            });

            (function () {
                var $slider = $("#slider");
                if ($slider.length > 0) {
                    $slider.slider({
                        min: 1,
                        max: 5,
                        value: 3,
                        orientation: 'horizontal',
                        range: 'min'
                    }).addSliderSegments($slider.slider('option').max);
                };

            })();

            
            
        });

        //Bootstrap Switch

        if ($('[data-toggle="switch"]').length) {
            $('[data-toggle="switch"]').bootstrapSwitch();
        }

        //Page Header Animation
        var $pageHeader = $(".page-header").find('h1[data-animation ^= "animated"]');
        doAnimation($pageHeader);

        //Tiles Animation
        var $tiles = $(".row").find('.tile[data-animation ^= "animated"]');
        doAnimation($tiles);

    </script>
</body>
</html>

NewMVC/Views/Flat/Materialize.cshtml
@{
    Layout = null;
    ViewBag.title = "Materialize Page";
}

<!DOCTYPE html>

<html lang="en">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>@ViewBag.title</title>

@*    @Scripts.Render("~/Content/css/frameworks")*@
@*    @Scripts.Render("~/Content/css/Animate")*@

    <link rel="shortcut icon" href="~/img/favicon.ico" />

    <link rel="stylesheet" type="text/css" href="~/bower_components/materialize/dist/css/materialize.css" media="screen,projection" />

    <style type="text/css">

        .container {
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }

        .row {
            margin-top: 1px;
        }

    </style>

</head>
<body ng-app="MaterializeModule">
    <div class="container">
        <div ui-view=""></div>
    </div>

    <div class="container">
        <div class="row">

    <ul class="collapsible popout" data-collapsible="accordion">
        <li>
            <div class="collapsible-header"><i class="mdi-image-filter-drama">First</i></div>
            <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.</p></div>
        </li>
        <li>
            <div class="collapsible-header"><i class="mdi-maps-place">Second</i></div>
            <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.</p></div>
        </li>
        <li>
            <div class="collapsible-header"><i class="mdi-social-whatshot">Second</i></div>
            <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.Lorem ipsum dolor sit amet.</p></div>
        </li>
    </ul>

</div>

    </div>

    @Scripts.Render("~/bundles/jquery")
@*    @Scripts.Render("~/bundles/js/frameworks")*@

    <script type="text/javascript" src="~/bower_components/angular/angular.js"></script>
    <script type="text/javascript" src="~/Scripts/angular-route.js"></script>
    <script type="text/javascript" src="~/Scripts/angular-resource.js"></script>
    <script type="text/javascript" src="~/bower_components/angular-animate/angular-animate.js"></script>
    <script type="text/javascript" src="~/bower_components/angular-aria/angular-aria.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/angular_material/0.8.3/angular-material.min.js"></script>
    <script type="text/javascript" src="~/bower_components/angular-ui-router/release/angular-ui-router.js"></script>
    <script type="text/javascript" src="~/bower_components/materialize/dist/js/materialize.js"></script>

    <script type="text/javascript" src="~/Scripts/app/directives/DirectDropDown.js"></script>
    <script type="text/javascript" src="~/Scripts/app/directives/DirectCard.js"></script>
    <script type="text/javascript" src="~/Scripts/app/controllers/MaterializeController.js"></script>
    <script type="text/javascript" src="~/Scripts/app/modules/MaterializeModule.js"></script>

    

    <script type="text/javascript">

        $(document).ready(function () {
           
            //Collapsible list initialization

            $(".collapsible").collapsible({
                accordion: false
            });

            

        });

    </script>

</body>
</html>

NewMVC/Views/Flat/PaperElements.cshtml
@{
    Layout = null;
}

<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <title>Polymer Elements</title>
        
        <script type="text/javascript" src="~/bower_components/webcomponentsjs/webcomponents.js"></script>
        <link rel="import" href="~/bower_components/paper-input/paper-input.html" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" />
        
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <paper-input floatingLabel label="Floating Label"></paper-input>
                </div>
            </div>
        </div>
        
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
        
    </body>
</html>