NewMVC/Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Category_ID { get; set; }
        public string Category_Name { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}

NewMVC/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using NewMVC.Models;

namespace NewMVC.Controllers
{
    public class CategoriesController : Controller
    {
        private NorthwindEntities db = new NorthwindEntities();
        public CategoriesController()
        {
            db.Configuration.ProxyCreationEnabled = false;
        }

        public ActionResult Index()
        {
            var categories = db.Categories.ToList();
            return View(categories);
        }

        public ActionResult search_category(int ID)
        {
            var found_category = db.Categories.Find(ID);
            
            if (found_category != null)
            {
                return Json(found_category, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return new HttpNotFoundResult("Matching records not found");
            }
        }

        [HttpPost]
        public ActionResult search_category_by_name(string category_name)
        {
            //string CategoryName = Request.QueryString["StateName"].ToString().Trim();
            var found_category = db.Categories.Where(m => m.Category_Name == category_name);
            if (found_category != null)
            {
                return Json(found_category.First(), JsonRequestBehavior.AllowGet);
            }
            else
            {
                return new HttpNotFoundResult("No matching records found");
            }
        }

        public PartialViewResult Create()
        {
            Category category = new Category();
            return PartialView("_CreateCategory", category);
        }

        public ActionResult CreateCategory()
        {
            Category category = new Category();
            return View(category);
        }

        [HttpPost]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
        }

        public ActionResult UpdateCategory(int ID)
        {
            var found_category = db.Categories.Find(ID);
            if (found_category != null)
            {
                return View(found_category);
            }
            else
            {
                return new HttpNotFoundResult("No matching records found");
            }
        }

        [HttpPost]
        public ActionResult Update(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();

                //var result = db1.Categories.Where(m => m.Category_Name == "some")
                //    .Where(m => m.Description == "something")
                //    .OrderBy(m => m.Category_ID)
                //    .Select(m => m).ToList();

                return RedirectToAction("Index");
            }
            else
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
        }

    }
}

NewMVC/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewMVC.Models;

namespace NewMVC.Controllers
{
    public class CustomersController : Controller
    {
        private NorthwindEntities db = new NorthwindEntities();
        public CustomersController()
        {
            db.Configuration.ProxyCreationEnabled = false;
        }

        public ActionResult Index()
        {
            var customers = db.Customers.ToList<Customer>();
            return View(customers);
        }

        public ActionResult GetOrderDetails(int id)
        {
            var order_details = db.Order_Details.Where(m => m.Order_ID == id);
            if (order_details != null)
            {
                return View(order_details.First());
            }
            else
            {
                return new HttpNotFoundResult("No matching records found");
            }
        }

        public ActionResult OrdersList(string customerID)
        {
            var order = db.Orders.Where(m => m.Customer_ID == customerID.Trim());
            if (order != null)
            {
                return View(order.ToList<NewMVC.Models.Order>());
            }
            else
            {
                return new HttpNotFoundResult("No matching records found");
            }
        }

        [HttpPost]
        public ActionResult SearchCustomerByName(string name)
        {
            var found_customer = db.Customers.Where(m => m.Contact_Name.Contains(name.Trim()));
            if (found_customer != null)
            {
                return Json(found_customer, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return new HttpNotFoundResult("No matching records found");
            }
        }

        [HttpPost]
        public ActionResult SearchCustomerByCompany(string company)
        {
            var found_customer = db.Customers.Where(m => m.Company_Name == company.Trim());
            if (found_customer != null)
            {
                return Json(found_customer, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return new HttpNotFoundResult("No matching records found");
            }
        }

        [HttpPost]
        public ActionResult SearchCustomerByCity(string city)
        {
            var found_customer = db.Customers.Where(m => m.City == city.Trim());
            if (found_customer != null)
            {
                return Json(found_customer, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return new HttpNotFoundResult("No matching records found");
            }

        }

        [HttpPost]
        public ActionResult SearchCustomerByCountry(string country)
        {
            var found_customer = db.Customers.Where(m => m.Country == country.Trim());
            if (found_customer != null)
            {
                return Json(found_customer, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return new HttpNotFoundResult("No matching records found");
            }
        }

    }
}

NewMVC/Views/Categories/CreateCategory.cshtml
@model NewMVC.Models.Category

@{
    Layout = "../Shared/_Layout.Phone.cshtml";
    ViewBag.title = "UpdateCategory.Phone.cshtml";
    ViewBag.message = "Updaet Category Page";
    ViewBag.ShowBackButton = true;
    ViewBag.ShowHomeButton = true;
    }

<div data-role="content" data-theme="b">
    @using (Html.BeginForm("Create", "Categories", FormMethod.Post))
    {
        <div class="ui-field-contain" hidden>
         @Html.DisplayNameFor(m => m.Category_ID)
         @Html.TextBoxFor(m => m.Category_ID)
     </div>
    <div class="ui-field-contain">
        @Html.DisplayNameFor(m => m.Category_Name)
        @Html.TextBoxFor(m => m.Category_Name)
    </div>
    <div class="ui-field-contain">
        @Html.DisplayNameFor(m => m.Description)
        @Html.TextBoxFor(m => m.Description)
    </div>
    <input type="submit" value="Submit" class="ui-btn ui-shadow ui-corner-all" />
    }
</div>

NewMVC/Views/Categories/Index.Phone.cshtml
@model IEnumerable<NewMVC.Models.Category>

@{
    Layout = "../Shared/_Layout.Phone.cshtml";
    ViewBag.title = "Index.Phone.cshtml";
    ViewBag.message = "Categories Page";
    ViewBag.ShowBackButton = true;
    ViewBag.ShowHomeButton = true;
}


    <div data-role="content" data-theme="b" id="IndexCategories">
    <div data-role="collapsible-set">
        <div data-role="collapsible" data-collapsed="true">
            <h2>List of Categories</h2>
            <div class="ui-grid-b" style="width: 100%;">
                <div class="ui-block-a">
                    <h3>Category ID</h3>
                </div>
                <div class="ui-block-b">
                    <h3>Category Name</h3>
                </div>
                <div class="ui-block-c">
                    <h3>Description</h3>
                </div>
                @foreach (var item in Model)
                {
                    <div class="ui-block-a">
                        <a href="@Url.Action("UpdateCategory", new { ID=@item.Category_ID })" data-transition="flip">@item.Category_ID</a>
                    </div>
                    <div class="ui-block-b">
                        <h4>@item.Category_Name</h4>
                    </div>
                    <div class="ui-block-c">
                        <h4>@item.Description</h4>
                    </div>
                }
            </div>
        </div>
        <div data-role="collapsible" data-collapsed="false">
            <h2>Search Category by ID & Name</h2>
            <div class="ui-grid-a">
                <div class="ui-block-a">
                    <select id="drpCategoryID" name="drpCategoryID" data-native-menu="false" data-icon="grid" data-iconpos="left">
                        @foreach (var item in Model)
                        {
                            <option>@item.Category_ID</option>
                        }
                    </select>
                </div>
                <div class="ui-block-b">
                    <select id="drpCategoryName" name="drpCategoryName" data-native-menu="false" data-icon="grid" data-iconpos="left">
                        @foreach (var item in Model)
                        {
                            <option>@item.Category_Name</option>
                        }
                    </select>
                </div>
            </div>
        </div>
        <div data-role="collapsed" data-collapsed="true">
            <a id="anchCreateCategory" href="@Url.Action("CreateCategory")" data-transition="flip" class="ui-btn ui-shadow ui-corner-all">Create New Category</a>
        </div>
    </div>
</div>


<a id="anchCategory" href="#pnlCategory" class="ui-btn ui-shadow ui-corner-all ui-btn-inline ui-btn-icon-left ui-icon-bars" data-transition="flow" style="display:none;"></a>
<div data-role="panel" data-theme="b" id="pnlCategory" data-display="overlay" style="width: 340px;">
    <div class="ui-content">
        <div class="ui-grid-a">

        </div>
    </div>
    
</div>


@section scripts {
    <script type="text/javascript">

        $(document).ready(function () {

            //alert('Index Category loaded');

            $("#drpCategoryID").change(function () {
                var id = $(this).val();
                var url = '@Url.Action("search_category")?ID=' + id;

                $.ajax({
                    url: url,
                    type: 'GET',
                    dataType: 'json',
                    success: function (response) {
                        $("#pnlCategory .ui-grid-a").empty();
                        var row_data = '<div class="ui-block-a"><h3>Category ID</h3></div>';
                        row_data += '<div class="ui-block-b"><h4>' + response.Category_ID + '</h4></div>';
                        row_data += '<div class="ui-block-a"><h3>Category Name</h3></div>';
                        row_data += '<div class="ui-block-b"><h4>' + response.Category_Name + '</h4></div>';
                        row_data += '<div class="ui-block-a"><h3>Description</h3></div>';
                        row_data += '<div class="ui-block-b"><h4>' + response.Description + '</h4></div>';
                        $("#pnlCategory .ui-grid-a").append(row_data);
                        $("#anchCategory").click();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status + " " + thrownError);
                    }
                });
            });

            $("#drpCategoryName").change(function () {
                var name = $(this).val();
                var url = '@Url.Action("search_category_by_name")';
                var data = { category_name: name };

                $.ajax({
                    url: url,
                    type: 'POST',
                    data: JSON.stringify(data),
                    contentType: 'application/json',
                    dataType: 'json',
                    success: function (response) {
                        $("#pnlCategory .ui-grid-a").empty();
                        var row_data = '<div class="ui-block-a"><h3>Category ID</h3></div>';
                        row_data += '<div class="ui-block-b"><h4>' + response.Category_ID + '</h4></div>';
                        row_data += '<div class="ui-block-a"><h3>Category Name</h3></div>';
                        row_data += '<div class="ui-block-b"><h4>' + response.Category_Name + '</h4></div>';
                        row_data += '<div class="ui-block-a"><h3>Description</h3></div>';
                        row_data += '<div class="ui-block-b"><h4>' + response.Description + '</h4></div>';
                        $("#pnlCategory .ui-grid-a").append(row_data);
                        $("#anchCategory").click();
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert(xhr.status + " " + thrownError);
                    }
                });
            });

        });

    </script>
}


NewMVC/Views/Categories/Index.cshtml
@model IEnumerable<NewMVC.Models.Category>

@{
    Layout = "../Shared/_Layout.cshtml";
    ViewBag.message = "Categories Page";
}


@section styles {
    <style type="text/css">
        body {
            background-color: white;
            background-position: center;
            background-repeat: no-repeat;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
        }
    </style>
}
    
    <div class="container">

        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="@Url.Action("Index")">
                        <img src="~/Content/Image/homelinkimg1.png" alt="Home" />
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="menu-nav">
                    <ul class="nav navbar-nav">
                        <li><a href="#" data-toggle="modal" data-target="#modalCreate">Create New State</a></li>
                        <li><a href="@Url.Action("Index", "Customers")">Customers Page</a></li>
                        <li><a href="#" data-toggle="modal" data-target="#modalArt">Show Art</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="row well">
            <div class="col-md-6">
                <form class="form-inline">
                    <div class="form-group">
                        <input type="text" class="form-control" id="txtSearch" placeholder="Enter Category ID" />
                    </div>
                    <button type="submit" class="btn btn-success" id="btnSearch">Search</button>
                </form>
            </div>
            <div class="col-md-6">
                <select id="CategoryName" class="selectpicker" style="width: auto;">
                    @foreach (var item in Model)
                    {
                        <option>@item.Category_Name</option>
                    }
                </select>
            </div>
        </div>

        <div class="row">
            <table class="table table-bordered table-condensed" id="tblCategory">
                <thead>
                    <tr>
                        <th>Category ID</th>
                        <th>Category Name</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.Label(item.Category_ID.ToString().Trim())</td>
                            <td>@Html.Label(item.Category_Name)</td>
                            <td>@Html.Label(item.Description)</td>
                            <td><a href='@Url.Action("search_category", new { id = @item.Category_ID })' class="btn btn-primary">Edit</a></td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>


    <!-- Modal -->

    <!-- Search Modal -->
    <div class="modal fade" id="modalSearchResult" tabindex="-1" role="dialog" aria-labelledby="search-result" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="search-result">Categories</h4>
                </div>
                <div class="modal-body">
                    <div class="well">
                        <table class="table table-bordered table-condensed">
                            <thead>
                                <tr>
                                    <th>Category ID</th>
                                    <th>Category Name</th>
                                    <th>Description</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <th>
                                        <label id="lblCategoryID"></label>
                                    </th>
                                    <th>
                                        <label id="lblCategoryName"></label>
                                    </th>
                                    <th>
                                        <label id="lblDescription"></label>
                                    </th>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Update Modal -->

    <div class="modal fade" id="modalUpdate" tabindex="-1" role="dialog" aria-labelledby="update" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="update">Update Category</h4>
                </div>
                <div class="modal-body">
                    <div class="row well">
                        <div class="col-md-6">
                            <form class="form-horizontal" action='@Url.Action("Update")' method="post">
                                @Html.ValidationSummary()
                                <div class="form-group" hidden>
                                    <h4>@Html.DisplayNameFor(m => m.First().Category_ID)</h4>
                                    @Html.TextBox("Category_ID", "", new { @class = "form-control", @id = "category_id" })
                                </div>
                                <div class="form-group">
                                    <h4>@Html.DisplayNameFor(m => m.First().Category_Name)</h4>
                                    @Html.TextBox("Category_Name", "", new { @class = "form-control", @id = "category_name" })
                                </div>
                                <div class="form-group">
                                    <h4>@Html.DisplayNameFor(m => m.First().Description)</h4>
                                    @Html.TextArea("Description", "", new { @class = "form-control", @id = "description" })
                                </div>
                                <input type="submit" class="btn btn-primary" value="Submit" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Create New Category -->

    <div class="modal fade" id="modalCreate" tabindex="-1" role="dialog" aria-labelledby="create" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="create">Create Category</h4>
                </div>
                <div class="modal-body">
                    <div class="row well">
                        @Html.Action("Create")
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Art Modal -->

    <div class="modal fade" id="modalArt" tabindex="-1" role="dialog" aria-labelledby="art" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="art">Show Art</h4>
                </div>
                <div class="modal-body">
                    <div class="row well">
                        <div id="carousel-art" class="carousel slide" data-ride="carousel">
                            <!-- Indicators -->
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-art" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-art" data-slide-to="1"></li>
                                <li data-target="#carousel-art" data-slide-to="2"></li>
                                <li data-target="#carousel-art" data-slide-to="3"></li>
                            </ol>

                            <!-- Wrapper for slides -->
                            <div class="carousel-inner" role="listbox">
                                <div class="item active">
                                    <img src="~/Content/Image/Inspir1.png" alt="art1">
                                </div>
                                <div class="item">
                                    <img src="~/Content/Image/Inspir2.png" alt="art2">
                                </div>
                                <div class="item">
                                    <img src="~/Content/Image/Inspir3.png" alt="art3">
                                </div>
                                <div class="item">
                                    <img src="~/Content/Image/Inspir4.png" alt="art4">
                                </div>
                            </div>

                            <!-- Controls -->
                            <a class="left carousel-control" href="#carousel-art" role="button" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="right carousel-control" href="#carousel-art" role="button" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@section scripts {
    <script type="text/javascript">

        function BindResult(response) {
            $("#lblCategoryID").html(response.Category_ID);
            $("#lblCategoryName").html(response.Category_Name);
            $("#lblDescription").html(response.Description);
            $("#modalSearchResult").modal('toggle');
        }

        $(document).ready(function () {

            $(".selectpicker").selectpicker({
                style: 'btn-info',
                size: 4
            });

            $("#tblCategory a").click(function (e) {
                e.preventDefault();
                var url = $(this).attr('href');

                $.ajax({
                    url: url,
                    type: 'GET',
                    dataType: 'json',
                    success: function (response) {
                        $("#category_id").val(response.Category_ID);
                        $("#category_name").val(response.Category_Name);
                        $("#description").val(response.Description);
                        $("#modalUpdate").modal('toggle');
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alertify.error(xhr.status + " " + thrownError);
                    }
                });
            });

            $("#btnSearch").click(function (e) {
                e.preventDefault();
                var search_string = $("#txtSearch").val();
                $.ajax({
                    url: 'http://localhost/NewMVC/categories/search_category/' + search_string,
                    type: 'GET',
                    dataType: 'json',
                    success: function (response) {
                        BindResult(response);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alertify.error(xhr.status + " " + thrownError.toString());

                    }

                });

            });

            $("#CategoryName").change(function () {
                var CategoryName = $(this).val();
                var data = { category_name: CategoryName };
                $.ajax({
                    url: '@Url.Action("search_category_by_name")',
                    type: 'POST',
                    data: JSON.stringify(data),
                    contentType: 'application/json',
                    dataType: 'json',
                    success: function (response) {
                        BindResult(response);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alertify.error(xhr.status + " " + thrownError);
                    }

                });

            });

        });

    </script>
}
    

NewMVC/Views/Categories/UpdateCategory.Phone.cshtml
@model NewMVC.Models.Category

@{
    Layout = "../Shared/_Layout.Phone.cshtml";
    ViewBag.title = "UpdateCategory.Phone.cshtml";
    ViewBag.message = "Updaet Category Page";
    ViewBag.ShowBackButton = true;
    ViewBag.ShowHomeButton = true;
    }

<div data-role="content" data-theme="b">
    @using (Html.BeginForm("Update", "Categories", FormMethod.Post))
{
     <div class="ui-field-contain" hidden>
         @Html.DisplayNameFor(m => m.Category_ID)
         @Html.TextBoxFor(m => m.Category_ID)
     </div>
    <div class="ui-field-contain">
        @Html.DisplayNameFor(m => m.Category_Name)
        @Html.TextBoxFor(m => m.Category_Name)
    </div>
    <div class="ui-field-contain">
        @Html.DisplayNameFor(m => m.Description)
        @Html.TextBoxFor(m => m.Description)
    </div>
    <input type="submit" value="Submit" class="ui-btn ui-shadow ui-corner-all" />
}
</div>

NewMVC/Views/Categories/_CreateCategory.cshtml
@model NewMVC.Models.Category

<div class="col-md-6">
    @using (Html.BeginForm("Create", "Categories", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.ValidationSummary()
        <div class="form-group" hidden>
            <h4>@Html.DisplayNameFor(m => m.Category_ID)</h4>
            @Html.TextBoxFor(m => m.Category_ID, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <h4>@Html.DisplayNameFor(m => m.Category_Name)</h4>
            @Html.TextBoxFor(m => m.Category_Name, new { @class = "form-control" })
        </div>
        <div class="form-group">
            <h4>@Html.DisplayNameFor(m => m.Description)</h4>
            @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
        </div>
        <input type="submit" class="btn btn-primary" value="Submit" />
    }
</div>

